### PR TITLE
reimplemented _anti_alias_step to use numpy

### PR DESCRIPTION
**Pull request by MM1nd**
Hello again,

anti_alias sported this comment:

> #TODO: There is probably a bit of numpy-optimization that can be done here.

That's exactly what I did. It is now much faster.

Cheers

Alex

### CODE REVIEW

**Comment by ftomassetti** [comment]
I am not numpy expert but if the tests pass I would vote to merge this. Thank you for your contribution!

**Comment by MM1nd** [comment]
Famous last words: Tests pass on my machine :)

**Comment by psi29a** [comment]
Out of curiosity, what is the performance change here?

**Comment by MM1nd** [comment]
Parameters:
-x 512 -y  256 -v --seed=7577

Current master:
Total Runtime: 1m15s (~16% of that in anti_alias). anti_alias is the second worst offender after _watermap related stuff (cf. #243)

This PR #244 :   
Total Runtime 55s (0.2% of that in anti_alias). _watermap now is by far the worst offender with ~32% of total runtime.

**Comment by psi29a** [comment]
Nice. :)

**Pull request merged**
