### PR TITLE
Added a test to provide better coverage for simulations/biome.py

### PR DESCRIPTION
**Pull request by esampson**
Requires biome_test.world which is pull request #4 on worldengine-data

### CODE REVIEW

**Comment by esampson** [comment]
Provides 98% coverage for simulations/biome.py

**Comment by ftomassetti** [comment]
Restarted tests on Travis

**Comment by psi29a** [comment]
Yay! :D

**Comment by ftomassetti** [comment]
I think we can merge it now. Great job!

**Pull request merged**
