### PR TITLE
Convert setters to properties

### LINKED ISSUE #209: Add property decorators in World
For example:

```python
@property
def elevation:
    return self.layers['elevation'].data
```

### PR DESCRIPTION
**Pull request by Himura2la**
Trying to be helpful and resolve #209
I did not run this project, so the code is need to be carevully reviewed and tested

### CODE REVIEW

**Comment by ftomassetti** [comment]
Any reasons why you did not run the automated tests locally?

**Comment by Himura2la** [comment]
To be honest, I don't have experience in unit testing. I tried to run `python -m unittest` but it discovered 0 tests. Maybe that's because I can't install `noise==1.2.2`, pip throws some random error

**Comment by ftomassetti** [comment]
To me it looks good and tests are passing. I will leave it open to give the possibility to @psi29a to take a look. If I do not hear anything in the next days I am going on to merge this one.

In the meantime: @Himura2la thank you very much for your work, it is appreciated!

**Comment by Himura2la** [comment]
Thanks for your opensource work!

**Comment by psi29a** [comment]
LGTM, merging! :)

Thank you very much!

**Comment by psi29a** [comment]
Feel free to add yourself to the list of contributors! :)

**Pull request merged**
