### PR TITLE
Master

### PR DESCRIPTION
**Pull request by pow450**

### CODE REVIEW

**Comment by tcld** [comment]
I might be overlooking it, but I don't see anything new in here. Is this maybe just a failed rebase?

**Comment by pow450** [comment]
Actually I didn't mean to send that through was showing a friend how to use github and didn't mean to send that
On Nov 29, 2015 2:43 PM, tcld <notifications@github.com> wrote:I might be overlooking it, but I don't see anything new in here. Is this maybe just a failed rebase?

**Comment by tcld** [comment]
Well, then you might want to show your friend how to close a PR, too.^^

**Comment by ftomassetti** [comment]
Hi @pow450 these things happen :) I am closing this PR but I hope in the future you will want to collaborate on WorldEngine! Enjoy GitHub

**Pull request closed without merging**
