### PR TITLE
manual: setup

### PR DESCRIPTION
**Pull request by ftomassetti**
I just setup the manual on readthedocs. It is visible here: http://worldengine.readthedocs.org/en/manual/

We could use this for user documentation. What do you think?

See #166

### CODE REVIEW

**Comment by esampson** [comment]
While I like online docs I am also a firm believer in supplying offline versions. Nothing worse than wanting to use a piece of software that doesn't require an internet connection but not being able to because you need to look something up and the manual does require one (which you currently lack, for some reason).

**Comment by ftomassetti** [comment]
You can also build the manual in several formats. We could generate it make it available either with the program or as a separate download.

**Comment by psi29a** [comment]
This is a nice start, but keep Sphinx in mind please. :)

**Comment by psi29a** [comment]
Nice start. :)

**Comment by ftomassetti** [comment]
stupid question: isn't sphinx what is used by readthedocs?

**Comment by ftomassetti** [comment]
I confirm that we can generate from the same format this:
```
Please use `make <target>' where <target> is one of
  html       to make standalone HTML files
  dirhtml    to make HTML files named index.html in directories
  singlehtml to make a single large HTML file
  pickle     to make pickle files
  json       to make JSON files
  htmlhelp   to make HTML files and a HTML help project
  qthelp     to make HTML files and a qthelp project
  applehelp  to make an Apple Help Book
  devhelp    to make HTML files and a Devhelp project
  epub       to make an epub
  latex      to make LaTeX files, you can set PAPER=a4 or PAPER=letter
  latexpdf   to make LaTeX files and run them through pdflatex
  latexpdfja to make LaTeX files and run them through platex/dvipdfmx
  text       to make text files
  man        to make manual pages
  texinfo    to make Texinfo files
  info       to make Texinfo files and run them through makeinfo
  gettext    to make PO message catalogs
  changes    to make an overview of all changed/added/deprecated items
  xml        to make Docutils-native XML files
  pseudoxml  to make pseudoxml-XML files for display purposes
  linkcheck  to check all external links for integrity
  doctest    to run all doctests embedded in the documentation (if enabled)
  coverage   to run coverage check of the documentation (if enabled)
```

So we should be able to provide offline manuals

**Comment by ftomassetti** [comment]
Let's merge this so that everyone is able to improve it

**Comment by psi29a** [comment]
Yes, RTD uses sphinx and our sphinx/config/python/rst files to generate the documents.

**Comment by tcld** [comment]
I just noticed that there are problems with the [manifest-test](https://travis-ci.org/Mindwerks/worldengine/jobs/89637800) in recent PRs. Seemingly introduced with #179 . I seem to always forget to check the optional tests. :(

**Comment by ftomassetti** [comment]
Which problems?

**Comment by tcld** [comment]
Rules need to be added to ```MANIFEST.in```, as suggested in the link I gave.

**Comment by psi29a** [comment]
Since documents (end result) is stored in RTD, we don't need to ship anything having to do with docs.

**Pull request merged**
