### PR TITLE
Announcing the merge and adding reference to the google group

### PR DESCRIPTION
**Pull request by ftomassetti**

### CODE REVIEW

**Comment by psi29a** [comment]
Travis isn't very happy. ;)

Missing world file in test suite.

**Comment by psi29a** [comment]
WorldSynth is re-licensed to MIT / Expat
https://github.com/psi29a/worldsynth/commit/2b2e9f8d8b42f34f512b923a96e1fdc636f795b1

**Comment by ftomassetti** [comment]
Cool!
P.S. Update the missing file and update the link to the Travis icon in the readme

**Comment by psi29a** [comment]
Looks good!

**Comment by ftomassetti** [comment]
thanks!

**Pull request merged**
