### PR TITLE
Appveyor

### PR DESCRIPTION
**Pull request by ftomassetti**
Fixed PyPlatec (and released), now WorldEngine can be built on AppVeyor

### CODE REVIEW

**Comment by ftomassetti** [comment]
It is working fine on a mac but there is a bad pointer error on Travis

**Comment by ftomassetti** [comment]
*** glibc detected *** /home/travis/virtualenv/python2.6.9/bin/python: malloc(): smallbin double linked list corrupted: 0x00000000054b7340 ***

:(

**Comment by ftomassetti** [comment]
I correct: now it is failing also on the mac ..........................................Python(10244,0x7fff726b8300) malloc: *** error for object 0x7fddc0649390: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug

**Comment by psi29a** [comment]
Looks good, added appveyor to Mindwerks/worldengine.

**Comment by psi29a** [comment]
Can you rebase, it won't automagically merge. :(

**Comment by ftomassetti** [comment]
It seems I forgot about this one.

We should _NOT_ merge this because it uses PyPlatec 1.2.10 which can cause segfaults :( :( :(
We need to release the new version of PyPlatec first

**Comment by ftomassetti** [comment]
ok, we released the new version of pyplatec and we updated worldengine to depends on 1.3.1 as part of this PR. Let me know if you prefer me to split the change of version to a single separate PR.

**Comment by psi29a** [comment]
This should be fine to merge in.

**Comment by ftomassetti** [comment]
Unfortunately there are new issues: the bindings for plate-tectonics works if compiled from the project directory, the Windows wheels should be also ok BUT the source distribution is broken because it does not include the C++ code (it is in the parent directory w.r.t. the python bindings directory). So we will have to release a new version on PyPi :( (see https://github.com/Mindwerks/plate-tectonics/issues/23)

**Comment by ftomassetti** [comment]
Now it succeed on Travis and fail on AppVeyor. Apparently it does not manage to build NumPy.

**Comment by ftomassetti** [comment]
Ok, it seems that it succeeded when pip was installed by our script and failed when it found pip already installed

Success:
```
Installing pip... 
Executing: C:\Python27/python.exe C:\get-pip.py 
 
Handles  NPM(K)    PM(K)      WS(K) VM(M)   CPU(s)     Id ProcessName           
-------  ------    -----      ----- -----   ------     -- -----------           
      7       4      380       1656    11     0.00   2352 python                
Collecting wheel
  Downloading wheel-0.24.0-py2.py3-none-any.whl (63kB)
Installing collected packages: wheel
 
Successfully installed wheel-0.24.0
```

Failure:
```
powershell appveyor\install.ps1
Installing Python 2.7.8 for 32 bit architecture to C:\Python27 
C:\Python27 already exists, skipping. 
False 
pip already installed. 
Downloading/unpacking wheel
Installing collected packages: wheel
Successfully installed wheel
Cleaning up...
```

**Comment by ftomassetti** [comment]
And also AppVeyor is happy now! Merging

**Comment by psi29a** [comment]
yay

**Pull request merged**
