### PR TITLE
fix loading pickle files

### PR DESCRIPTION
**Pull request by ftomassetti**
Apparently loading pickle files does not work anymore. Fixing.
Also adding a few spaces before the name of the operation, so that everything is aligned.

### CODE REVIEW

**Comment by tcld** [comment]
It didn't work? At least one of the files used by the unit tests is a pickle file, and I never noticed any problems. Or was it just with user-loaded pickle files?

**Comment by ftomassetti** [comment]
it was with user loaded pickle files: we have a function which look at a world file and try to guess if it is a pickle file or a protobuf file and depending on that load the world with a different function. The issue was with the function recognizing the type of file. Perhaps in the tests we call directly the method to load a file from pickle.

**Comment by ftomassetti** [comment]
It is failing because of changes with the blessed images.

**Comment by tcld** [comment]
You are right about the way the pickle files are loaded in the tests.

I wouldn't mind if you just merged this, if that isn't against standard procedure. The change is kind of small.^^

**Comment by ftomassetti** [comment]
#168 was built on top of this so no need to merge this one separately

**Pull request closed without merging**
