### PR TITLE
Adopt pyplatec 1.4.0

### PR DESCRIPTION
**Pull request by ftomassetti**
Let's take advantage of the speed improvements we got in the new version of plate-tectonics/pyplatec

### CODE REVIEW

**Comment by tcld** [comment]
This is really, really great! When I last checked, about 25% of the overall time needed to generate a world went into platec. That could go down to a negligible amount.
I am not sure how my perf_opt-branch (https://github.com/Mindwerks/worldengine/pull/132) does with large worlds, but for smaller ones it already decreased generation times by about 25%. So overall a speed-up of up to a factor of 2 would be feasible for the "next version".

**Comment by psi29a** [comment]
Looking good, merging!

@ftomassetti have you been in contact with our Finnish counterpart? We going to be up-streaming our patches?

**Comment by ftomassetti** [comment]
Nope, I have not being in contact since he said he was leaving for holidays. I think our fork diverged quite a bit, I hope they are fine accepting our patches. Perhaps it is time to write again to them to present the significantly speedup we got (admittedly, it is possible that I slow down our code while refactoring and this speedup just makes as fast as platec was already originally :D, we should measure that)

**Comment by psi29a** [comment]
Check your email, he sent something awhile back with you in CC. I'll forward it to you.

**Comment by psi29a** [comment]
@ftomassetti I forwarded you the email he sent (with you in CC) in Sept. So he is back and has a plan. I also sent a reply. You sure you didn't get that?

**Pull request merged**
