### PR TITLE
Fixes to make pyflakes- and manifest-tests run again.

### PR DESCRIPTION
**Pull request by tcld**
Problem described here: https://github.com/Mindwerks/worldengine/issues/158

I used @psi29a 's suggestion regarding the addition to ```MANIFEST.in```.

### CODE REVIEW

**Comment by tcld** [comment]
About the tests: The ancient map-stuff should pass once the RNG-changes are merged.

However, the manifest-tests still fail: https://travis-ci.org/Mindwerks/worldengine/jobs/88091783
Does somebody know what do do about it?

**Comment by tcld** [comment]
@psi29a: Do you maybe have a hint about what to do to make the manifest-test pass again?

**Comment by tcld** [comment]
I read about ```MANIFEST.in``` and the two optional tests can now be passed again. I excluded the ```docs```-directory (and thus ```Biomes.html```) in ```MANIFEST.in``` - is that the right way to go? If so, this could be merged to make two of the tests run again.

Maybe one of you can have a look at the (tiny) changes, @ftomassetti or @psi29a ?
I also wouldn't mind making the pyflakes-test a non-optional test, since it provides very clear instructions on what to change (and so far it has proven quite useful in my opinion).

**Comment by ftomassetti** [comment]
I think we should include the docs directory in MANIFEST.in, so that the user downloading the package have also the docs.

**Comment by ftomassetti** [comment]
Aside from including the docs all the rest seems good to me

**Comment by tcld** [comment]
So I should use ```recursive-include``` instead? I am not sure if the the test will pass then, but I can try.

**Comment by tcld** [comment]
Ok, it seems to work.

**Comment by ftomassetti** [comment]
cool, merging

**Pull request merged**
