### PR TITLE
PDF creation from RTD

### PR DESCRIPTION
**Pull request by esampson**
It turns out that while the images show up if you are viewing the manual online through RTD they don't show up properly in the downloaded HTMLzip or PDFs unless the images are moved into a subdirectory of the directory containing the RST file.

Additionally I had to add some specific commands when rendering the PDF through LaTex to make the images come out better.

### CODE REVIEW

**Comment by psi29a** [comment]
I'm going to veto this, no binary data in worldengine please.

What you can do is use the URL to worldengine-data instead.

If that isn't solvable, then we need to move our docs to worldengine-data.

**Comment by esampson** [comment]
We can move the docs to worldengine-data. That should be very easy. As I understand it all we need to do is copy the files and then change the entry in ReadTheDocs to point to the different git distribution.

There is one issue, however, that is indirectly connected to this. The work that I'm doing with an alternative system for drawing ancient maps (https://github.com/Mindwerks/worldengine/issues/177) requires at least one PNG file (or some other form of non-readable file. I could use an asciii encode of the PNG, but what would be the point to that?).

We could start a third git repository for alternate styles but I think we should include at least a single default style so that the routine works 'out of the box'. There are other options. The first I can think of is that I believe I can reference the file remotely (through http), but that would mean that the computer has to have an internet connection to use the routine, which I don't like. The other possibility would be to make the new routine a plugin and give it and other plugins their own git repository.

**Comment by esampson** [comment]
Oh. I should add that my first version did use the URL to worldengine-data. While it produced good results when looking at the ReadTheDocs website the images were not included in the HTMLzip or PDF files.

**Comment by esampson** [comment]
Just a quick note to confirm, you can simply redirect the document project to an alternate git repository.

**Pull request closed without merging**
