### PR TITLE
pickle: protobuf: make protobuf the default format instead of pickle

### PR DESCRIPTION
**Pull request by ftomassetti**
Solve #65

### CODE REVIEW

**Comment by psi29a** [comment]
Can we just drop 'official' support of pickle, as in in the params?  We leave the code to handle pickle worlds until 0.20 ?

**Comment by ftomassetti** [comment]
sure, done

**Comment by ftomassetti** [comment]
Cool, one to go before closing all the issues for v0.19.0

**Comment by tcld** [comment]
@ftomassetti and @psi29a:
I just realized that removing the ability to save pickle-files kind of makes it impossible to generate test-worlds in the pickle-format.
So either there needs to be some kind of backdoor or the pickle-tests etc. should be removed, too. (I think only the latter makes sense since loading of old pickle-worlds will fail anyway once there has been any sort of change to the save files. So the end-user won't have any advantage from residual pickle-support).

**Comment by psi29a** [comment]
The later is the best, it should also be purged. Tests can go away.

**Comment by tcld** [comment]
I took some time and removed pickle completely: https://github.com/Mindwerks/worldengine/pull/192

**Pull request merged**
